### ISSUE TITLE
Israel NBCTF

### ISSUE THREAD

**Issue by Ketoch** [opensanctions/crawler-planning#102]
### Data URL

https://nbctf.mod.gov.il/en/Pages/default.aspx

### Publisher

National Bureau for Counter Terror Financing of Israel

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Data is here: https://nbctf.mod.gov.il/en/Minister%20Sanctions/Designation/Pages/downloads.aspx 

I think this is the same as: https://www.opensanctions.org/datasets/il_mod_terrorists/ - can you check, @Ketoch ?

**Comment by Ketoch** [comment]
yes @pudo, u are right. It is the same. Sorry for mistake

**Comment by pudo** [comment]
great, no problem!
