### ISSUE TITLE
Nepal MHA

### ISSUE THREAD

**Issue by Ketoch** [opensanctions/crawler-planning#105]
### Data URL

https://moha.gov.np/post/sanction-list-1

### Publisher

Nepal

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Hey @Ketoch - thanks for all these list ideas! Keep 'em coming! :)
