### ISSUE TITLE
Indonesia DTTOT

### ISSUE THREAD

**Issue by Ketoch** [opensanctions/crawler-planning#109]
### Data URL

https://www.ppatk.go.id/link/read/23/dttot-proliferasi-wmd.html

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
should WMD be on a separate card or included here?
