### ISSUE TITLE
Thailand AMLO

### ISSUE THREAD

**Issue by Ketoch** [opensanctions/crawler-planning#110]
### Data URL

https://amlo.go.th/index.php/en/high-risk-countries-designated-list/2016-06-04-14-50-52

### Publisher

AMLO

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
Holding this one for Klil
