### ISSUE TITLE
Members of the Estonian Parliament

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#12]
https://www.riigikogu.ee/en/parliament-of-estonia/composition/members-riigikogu/

**Comment by ErkoRisthein** [comment]
There's also a free open data API by the parliament of Estonia: https://www.riigikogu.ee/en/open-data/
Here's the Swagger UI: https://api.riigikogu.ee/swagger-ui.html
And here's the request to get all members of the parliament: https://api.riigikogu.ee/api/plenary-members?lang=EN
It has dates of birth as well.

**Comment by dhdaines** [comment]
Thanks!  It would be very strange if there were not an API for this, it is Estonia after all :)
