### ISSUE TITLE
Serbian sanctions list

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#122]
### Data URL

https://www.apml.gov.rs/english/lists-of-designated-persons-search-engine

### Publisher

APML

### Publisher country/territory code

RS

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Europe

### Can you tell us more?

See also: https://www.apml.gov.rs/english/targeted-financial-sanctions 

The national list seems to be a badly scanned PDF :/ 

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
looks like a PDF needing OCR or manual entry by a cyrillic user

**Comment by jbothma** [comment]
google translate

![Image](https://github.com/opensanctions/crawler-planning/assets/235801/20918af2-88de-4362-a751-f43785b61b88)

```
They are placed on the list of designated persons:
1) Abid (Đule) Podbićanin, born on March 15, 1979. year in
Prijepolje, with residence in Novi Pazar, 111 Hadžet Street, citizen of
the Republic of Serbia, is on the run;
2) Sead (Omer) Plojović, born on March 16, 1983. year in Novi Pazar,
with residence in Novi Pazar, Ulica Sarajevska number 13, citizen of the
Republic of Serbia and the Republic of Croatia;
3) Izudin (Mustafa) Crnovrsanin, born on March 27, 1989.
year in Novi Pazar, with residence in Novi Pazar, 108 Sutjeska Street,
citizen of the Republic of Serbia;
4) Ferat (Skender) Kasumović, born on March 14, 1984. in Belgrade,
Zemun, with residence in Belgrade, Petra Drapšina Street number 25,
citizen of the Republic of Serbia;
5) Tefik (Tahir) Mujović, born on September 8, 1980. year in
Tutin, with residence in Novi Pazar, Street 404 bb, citizen of the Republic of Serbia;
6) Goran (Tomislav) Pavlović, born on January 6, 1966. in Belgrade,
with residence in Belgrade, Ulica Kamenogorska number 10/2, citizen of
the Republic of Serbia, is on the run and
7) Rejhan (Muamer) Plojović, born on January 8, 1986. year
in Novi Pazar, with residence in Novi Pazar, Street 408 number 2, citizen
of the Republic of Serbia, is on the run.
```

**Comment by jbothma** [comment]
csv link published to web https://docs.google.com/spreadsheets/d/e/2PACX-1vTnxl3-xyO-9BBqM-rwJB849Kwm3-8ucrzVYZPl2-xhxky8DF4d485mrsyYyR266ePtK2-Qtpcz13jz/pub?output=csv

edit link https://docs.google.com/spreadsheets/d/1ceZADT99E8JJdA438C-lflzFDkewyKdH-yO30QyD0E4/edit#gid=0

**Comment by pudo** [comment]
Candidate for using GPT-4o extraction.

**Comment by pudo** [comment]
Included now with hash change detection
