### ISSUE TITLE
Japan Trade and Industry End User List

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#137]
### Data URL

https://www.meti.go.jp/english/policy/external_economy/trade_control/index.html

### Publisher

https://www.meti.go.jp/english/index.html

### Publisher country/territory code

jp

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:Asia/Pacific

### Can you tell us more?

The Ministry of Economy, Trade and Industry (METI) has issued the End User List, providing exporters with information on foreign entities for which concern cannot be eliminated regarding involvement in activities such as the development of weapons of mass destruction (WMDs) and other items.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Fixed in https://www.opensanctions.org/datasets/jp_meti_eul/
