### ISSUE TITLE
Canada Consolidated Autonomous Sanctions List

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#138]
### Data URL

https://www.international.gc.ca/world-monde/international_relations-relations_internationales/sanctions/consolidated-consolide.aspx?lang=eng

### Publisher

https://www.canada.ca/en.html

### Publisher country/territory code

ca

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### This is a suggestion or request

- [X] I understand.

**Comment by Kaldea** [comment]
See: https://www.opensanctions.org/datasets/ca_dfatd_sema_sanctions/
