### ISSUE TITLE
Canada Corrupt Foreign Nationals

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#139]
### Data URL

https://laws-lois.justice.gc.ca/eng/regulations/SOR-2017-233/page-2.html#h-842596

### Publisher

https://laws-lois.justice.gc.ca

### Publisher country/territory code

ca

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:North America

### Can you tell us more?

An individual whose name is listed in the schedule is a foreign national who, in the opinion of the Governor in Council, has committed an act set out in subsection 4(2) of the Justice for Victims of Corrupt Foreign Officials Act (Sergei Magnitsky Law).

### This is a suggestion or request

- [X] I understand.

**Comment by Kaldea** [comment]
See: https://www.opensanctions.org/datasets/ca_dfatd_sema_sanctions/
