### ISSUE TITLE
Canada Freezing Assets of Corrupt Foreign Officials (Tunisia)

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#140]
### Data URL

https://laws-lois.justice.gc.ca/eng/regulations/SOR-2011-78/FullText.html

### Publisher

https://laws-lois.justice.gc.ca

### Publisher country/territory code

ca

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### Can you tell us more?

Tunisia and Egypt have asserted to the Government of Canada, in writing, that each of the persons listed has misappropriated property of Tunisia or of Egypt, as the case may be, or have acquired property inappropriately by virtue of their office or a personal or business relationship and have asked the Government of Canada to freeze the property of those persons.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
See: https://www.opensanctions.org/programs/CA-FACFOA/
