### ISSUE TITLE
Canada Regulations Establishing a List of Entities

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#142]
### Data URL

https://laws-lois.justice.gc.ca/eng/regulations/SOR-2002-284/page-1.html

### Publisher

https://laws-lois.justice.gc.ca

### Publisher country/territory code

ca

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

[Regulations Establishing a List of Entities](https://laws-lois.justice.gc.ca/eng/regulations/SI-2008-143) has knowingly carried out, attempted to carry out, participated in or facilitated a terrorist activity or is knowingly acting on behalf of, at the direction of or in association with an entity that has knowingly carried out, attempted to carry out, participated in or facilitated a terrorist activity;

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
cf. https://www.opensanctions.org/datasets/ca_listed_terrorists/
