### ISSUE TITLE
North Korea Sanctions and Enforcement Actions Advisory

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#143]
### Data URL

https://www.cbp.gov/document/report/north-korea-sanctions-and-enforcement-actions-advisory

### Publisher

https://www.cbp.gov

### Publisher country/territory code

us

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

CBP and ICE, with the U.S. Department of State, and the U.S. Department of the Treasury's Office of Foreign Assets Control (OFAC), issued the North Korea Sanctions and Enforcement Actions Advisory: Risks for Businesses with Supply Chain Links to North Korea on July 23, 2018.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Spreadsheet here: https://docs.google.com/spreadsheets/d/1frGePFNXZhzpHYDTtpFaqPKMz8mQFo2OVCKlZ47OEJ0/edit?gid=0#gid=0 

I think we could add this to `us_special_leg` but make sure we add context and don't mark them with topic sanction, but perhaps `reg.warn` or `export.risk` ....

**Comment by bgmello** [comment]
@pudo I don't have access to the spreadsheet. Can you make it public so we can use it in the crawler?

**Comment by pudo** [comment]
I'm sorry! It's fixed now: https://docs.google.com/spreadsheets/d/e/2PACX-1vRfovKtSGNW3_tS80_-Aa25g3utwny-8Oyoi0CAy9kGke4mbIVVFel9Xgy28NlFFwutRroiVW605NXo/pub?gid=0&single=true&output=csv
