### ISSUE TITLE
BIS Entity List

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#144]
### Data URL

https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/entity-list

### Publisher

https://www.bis.gov

### Publisher country/territory code

us

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

The Export Administration Regulations (EAR) contain a list of names of certain foreign persons – including businesses, research institutions, government and private organizations, individuals, and other types of legal persons – that are subject to specific license requirements for the export, reexport and/or transfer (in-country) of specified items. These persons comprise the Entity List, which is found in Supplement No. 4 to Part 744 of the EAR. On an individual basis, the persons on the Entity List are subject to licensing requirements and policies supplemental to those found elsewhere in the EAR.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
See: https://www.opensanctions.org/programs/US-BIS-EL/
