### ISSUE TITLE
BIS Unverified List

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#145]
### Data URL

https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/unverified-list

### Publisher

https://www.bis.gov

### Publisher country/territory code

us

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

Parties listed on the Unverified List (UVL) are ineligible to receive items subject to the Export Administration Regulations (EAR) by means of a license exception. In addition, exporters must file an Automated Export System record for all exports to parties listed on the UVL and obtain a statement from such parties prior to exporting, reexporting, or transferring to such parties any item subject to the EAR which is not subject to a license requirement. Restrictions on exports, reexports and transfers (in-country) to persons listed on the UVL are set forth in [Section 744.15](http://www.ecfr.gov/cgi-bin/text-idx?rgn=div5&node=15:2.1.3.4.28#15:2.1.3.4.28.0.1.15) of the EAR. The Unverified List is set forth in [Supplement No. 6 to Part 744](https://www.bis.doc.gov/index.php/component/docman/?task=doc_download&gid=2713) of the EAR.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
see: https://www.opensanctions.org/programs/US-BIS-UVL/
