### ISSUE TITLE
BIS Military End User List

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#146]
### Data URL

https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/1770

### Publisher

https://www.bis.gov

### Publisher country/territory code

us

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

The Military End User List ([Supplement No. 7 to part 744](https://www.bis.doc.gov/index.php/component/docman/?task=doc_download&gid=2714) of the EAR) identifies foreign parties that are prohibited from receiving items described in Supplement No. 2 of Part 744 of the EAR unless the exporter secures a license.  These parties have been determined by the U.S. Government to be ‘military end users,’ as defined in [Section 744.21(g)](https://www.bis.doc.gov/index.php/documents/regulations-docs/2343-part-744-control-policy-end-user-and-end-use-based-2/file) of the EAR, and represent an unacceptable risk of use in or diversion to a ‘military end use’ or ‘military end user’ in China, Russia, or Venezuela.
  
The Military End User List is not exhaustive, and, pursuant to the license requirements in [Section 744.21](https://www.bis.doc.gov/index.php/documents/regulations-docs/2343-part-744-control-policy-end-user-and-end-use-based-2/file) of the EAR,  exporters, reexporters, or transferors must conduct their own due diligence for entities not identified in [Supplement No. 7 to Part 744](https://www.bis.doc.gov/index.php/component/docman/?task=doc_download&gid=2714) of the EAR.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
see: https://www.opensanctions.org/programs/US-BIS-MEU/
