### ISSUE TITLE
Council Regulation (EU) 2022/398

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#147]
### Data URL

https://eur-lex.europa.eu/eli/reg/2022/398/oj

### Publisher

https://eur-lex.europa.eu/homepage.html

### Publisher country/territory code

eu

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Europe

### Can you tell us more?

Council Regulation (EU) 2022/398 of 9 March 2022 amending Regulation (EC) No 765/2006 concerning restrictive measures in view of the situation in Belarus and the involvement of Belarus in the Russian aggression against Ukraine

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
cf. https://www.opensanctions.org/programs/EU-BRUS/
