### ISSUE TITLE
Council Implementing Regulation (EU) 2022/2476

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#148]
### Data URL

https://eur-lex.europa.eu/eli/reg_impl/2022/2476/oj

### Publisher

https://eur-lex.europa.eu/homepage.html

### Publisher country/territory code

eu

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Europe

### Can you tell us more?

Council Regulation (EU) 2022/2476 of 16 December 2022 implementing Regulation (EU) No 269/2014 concerning restrictive measures in respect of actions undermining or threatening the territorial integrity, sovereignty and independence of Ukraine.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
cf. https://www.opensanctions.org/programs/EU-UKRAINE-INTEG/
