### ISSUE TITLE
US Terrorist Exclusion List

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#150]
### Data URL

https://www.state.gov/terrorist-exclusion-list/

### Publisher

https://www.state.gov

### Publisher country/territory code

us

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

Section 411 of the USA PATRIOT ACT of 2001 (8 U.S.C. § 1182) authorized the Secretary of State, in consultation with or upon the request of the Attorney General, to designate terrorist organizations for immigration purposes. This authority is known as the “Terrorist Exclusion List (TEL)” authority.

### This is a suggestion or request

- [X] I understand.

**Comment by Kaldea** [comment]
See: https://www.opensanctions.org/datasets/us_state_terrorist_exclusion/
