### ISSUE TITLE
US Section 7031(c) of the DoS, Foreign Operations, and Related Programs Appropriations Act

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#151]
### Data URL

https://www.state.gov/reports/report-to-congress-on-anti-kleptocracy-and-human-rights-visa-restrictions-public-listing/

### Publisher

https://www.state.gov

### Publisher country/territory code

us

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

Section 7031(c) of the Department of State, Foreign Operations, and Related Programs Appropriations Act, Congress provides that officials of foreign governments and their immediate family members are ineligible for entry into the United States when the Secretary of State has credible information that the foreign official has been involved, directly or indirectly, with significant corruption and/or a gross violation of human rights.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
cf. https://www.opensanctions.org/datasets/us_klepto_hr_visa/
