### ISSUE TITLE
Luxembourg Administrative sanctions

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#157]
### Data URL

https://www.cssf.lu/fr/publications-donnees/?content_type=1387%2C623%2C625

### Publisher

https://www.cssf.lu/fr/

### Publisher country/territory code

lu

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Europe

### Can you tell us more?

The Commission de Surveillance du Secteur Financier (CSSF) of Luxembourg conducts its prudential and market surveillance missions with the aim of contributing to the soundness and stability of the financial sector, exclusively in the public interest.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
We'll only get names from this and sourceUrl, but that's good enough. Please tag `reg.warn` :)
