### ISSUE TITLE
Executive Order 13959

### ISSUE THREAD

**Issue by bgmello** [opensanctions/crawler-planning#160]
### Data URL

https://en.wikipedia.org/wiki/Executive_Order_13959

### Publisher

https://trumpwhitehouse.archives.gov/presidential-actions/executive-order-addressing-threat-securities-investments-finance-communist-chinese-military-companies/

### Publisher country/territory code

us

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:North America

### Can you tell us more?

The President of the United States manages the operations of the Executive branch of Government through Executive Orders. The Executive Order 13959 of November 12, 2020 is addressing the threat from securities investments that finance communist Chinese military companies.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
cf. https://www.opensanctions.org/programs/US-CHINA-MIL/
