### ISSUE TITLE
parltrack as source of european MEPs

### ISSUE THREAD

**Issue by RMHogervorst** [opensanctions/crawler-planning#161]
### Data URL

https://parltrack.org/dumps

### Publisher

https://parltrack.org/

### Publisher country/territory code

eu

### Type of data

PEPs (Politicall Exposed Persons)

### Coverage region

region:Europe

### Can you tell us more?

I do not know how good the coverage of MEPs is currently, but this dataset would make it much easier to get an overview.
The data seems very structured. 

tbh I stumbled upon this project on mastodon in the past week and immediately thought of opensanctions, but I did no deep dive into the dataset (there is a separate dump of MEP basic information inclusing twitter handle, first, last name, country etc: https://parltrack.org/schemas/ep_meps ). 

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Haha, lovely! I'm a big fan of stf and his work :) We're crawling the official XML about MEPs from the parliament, which seems like a more explainable source. 

One day we'll also make good links between parltrack and https://investigraph.eu/ :)
