### ISSUE TITLE
Malaysia Securities Commission Investor Alert List

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#166]
### Data URL

https://www.sc.com.my/investor-alert-list

### Publisher

Suruhanjaya Sekuriti

### Publisher country/territory code

MY

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:Asia/Pacific

### This is a suggestion or request

- [X] I understand.

**Comment by Fe1777** [comment]
Integrate Malaysia SC Investor Alert List:

### Step 1: Familiarize with the Source
1. **Visit the Malaysia Securities Commission's Website:**
   - Go to the [Malaysia Securities Commission's Investor Alert List](https://www.sc.com.my/investors/sc-investor-alerts).
   - Understand the structure of the data provided. Determine if the data is available in HTML format, as a downloadable file (CSV, Excel), or another format.

### Step 2: Set Up the Development Environment
1. **Fork and Clone the Repository:**
   - Go to the [opensanctions/crawler-planning GitHub page](https://github.com/opensanctions/crawler-planning).
   - Click the "Fork" button to create a personal copy of the repository.
   - Clone your fork locally with:
     ```bash
     git clone https://github.com/your-username/crawler-planning
     cd crawler-planning
     ```

2. **Setting Up Dependencies:**
   - Ensure you have Python installed (recommend Python 3.7+).
   - Create and activate a virtual environment:
     ```bash
     python -m venv env
     source env/bin/activate  # On Windows use `env\Scripts\activate`
     ```
   - Install the necessary dependencies:
     ```bash
     pip install -r requirements.txt
     ```

### Step 3: Create a New Crawler
1. **Create the Crawler Script:**
   - Inside the `crawlers` directory (create one if it doesn't exist), create a new file named `malaysia_sc_alerts.py`.
   - Open the `malaysia_sc_alerts.py` file in a text editor or IDE.

2. **Implement the Crawler:**
   - Below is a basic structure to start with:

```python
import requests
from bs4 import BeautifulSoup
import json
from opensanctions import Dataset

def fetch_data():
    url = 'https://www.sc.com.my/investors/sc-investor-alerts'
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # This part will vary depending on the structure of SC's website
    # Usually, you might have to find the right table or list
    data_list = []  # Temporary structure to store parsed data

    # Example: parsing table rows
    for row in soup.find_all('tr'):
        cols = row.find_all('td')
        if cols:
            entity = {
                'name': cols[0].text.strip(),
                'details': cols[1].text.strip()
            }
            data_list.append(entity)

    return data_list

def main():
    data = fetch_data()
    dataset = Dataset('malaysia_sc_alerts', title='Malaysia Securities Commission Investor Alerts')
    
    for entry in data:
        entity = dataset.make_entity(entry['name'], type='Person')
        entity.add('details', entry['details'])
        dataset.save(entity)
    
if __name__ == '__main__':
    main()
```

### Step 4: Test the Crawler
1. **Run the Script:**
   - Make sure your virtual environment is activated.
   - Run the script to check if it correctly fetches and parses the data:
     ```bash
     python crawlers/malaysia_sc_alerts.py
     ```
   - Fix any issues or errors that arise.

### Step 5: Submit a Pull Request
1. **Commit and Push Your Changes:**
   - Stage the changes:
     ```bash
     git add crawlers/malaysia_sc_alerts.py
     ```
   - Commit with a meaningful message:
     ```bash
     git commit -m "Add Malaysia Securities Commission Investor Alert List crawler"
     ```
   - Push the changes to your fork:
     ```bash
     git push origin main
     ```

2. **Open a Pull Request:**
   - Go to the original `opensanctions/crawler-planning` repository.
   - You should see a prompt to open a Pull Request (PR).
   - Provide a clear title and description for your PR, summarizing your changes and any specifics about the data source.

### Step 6: Review and Merge
1. **Engage with Maintainers:**
   - Watch for feedback or requests from the repository maintainers.
   - Make any requested changes and continue the discussion as needed.

2. **Merge the PR:**
   - Once approved, your PR will be merged into the main repository.

### Additional Considerations:
- **Error Handling:** Ensure your script can handle common errors gracefully, such as network issues or changes in the HTML structure.
- **Data Validation:** Check for duplicate entries or malformed data.
- **Documentation:** Include comments in your code explaining key parts of the logic and ensure your PR description is clear.
