### ISSUE TITLE
Israel Weapons of Mass Destruction Banned Entities List

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#167]
### Data URL

https://www.gov.il/en/pages/declared_elements_list

### Publisher

Israel Ministry of Finance

### Publisher country/territory code

IL

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Asia/Pacific

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
Discussing in slack:

> as far as I can tell, the main difference between https://github.com/opensanctions/crawler-planning/issues/167 and UN Resolutions 2231 and 1718 is that they add the following columns, for which the value is always July 12th 2018 or April 1, 2018 (the latter only in the permanent column)
> - "The date of adoption of the declaration in Israel(temporary automatic adoption)"
> -  "The date of adoption of the declaration in Israel (permanent adoption)"
>
> it almost sounds like there should be more, but they're not in the linked files.
> shall we just include this excel file with these as start dates? Should the program perhaps be Prevention of Distribution and Financing of Weapons of Mass Destruction Law – 2018?
> it looks like these resolutions are not in UN SC consolidated?
