### ISSUE TITLE
List of Chinese telecommunications companies excluded from US federal contracts (889 List)

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#168]
### Data URL

https://www.congress.gov/115/plaws/publ232/PLAW-115publ232.pdf

### Publisher

US Congress

### Publisher country/territory code

US

### Type of data

Debarment (Entities banned from participating in public contracting)

### Coverage region

region:North America

### Can you tell us more?

The list of PRC telecommunications companies designated under Section 889 of the National Defense Authorization Act for FY 2019 (889 List) as posing national security risks to the United States. Section 889 prohibits federal contractors from providing the U.S. government with equipment from five PRC companies, their subsidiaries, and their affiliates.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Included in `us_special_leg`: https://www.opensanctions.org/programs/US-MCCAIN-889/
