### ISSUE TITLE
China National People's Congress

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#170]
### Data URL

http://en.npc.gov.cn.cdurl.cn/

### Publisher

PRC

### Publisher country/territory code

CN

### Type of data

PEPs (Politicall Exposed Persons)

### Coverage region

region:Asia/Pacific

### Can you tell us more?

I cannot immediately identify if a list of the deputies is available.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
@bgmello - Would you be up for doing a little round of research on this and see what sources are available online?

**Comment by bgmello** [comment]
I'll take a look to see if I can find the source

**Comment by bgmello** [comment]
At first didn't find anything on the official website, but then I found this site called [NPC Observer](https://npcobserver.com/2023/02/china-14th-npc-demographics/) which has information about the National People Congress for people outside China. They then had a link to the official website [with the list](http://www.npc.gov.cn/c2/kgfb/202302/t20230225_423685.html), but it's not properly formatted. Fortunately, they created an excel file with the [data](https://docs.google.com/spreadsheets/d/1BzGKorkaqx3sjx7ohHULDZadVqgGUjER/edit#gid=1077635225), and also added to [Wikipedia](https://zh.wikipedia.org/wiki/%E7%AC%AC%E5%8D%81%E5%9B%9B%E5%B1%8A%E5%85%A8%E5%9B%BD%E4%BA%BA%E6%B0%91%E4%BB%A3%E8%A1%A8%E5%A4%A7%E4%BC%9A%E4%BB%A3%E8%A1%A8%E5%90%8D%E5%8D%95). So I guess we can use that

**Comment by pudo** [comment]
Very nice finds! It looks like the Wikipedia list has DOBs -- should we make that into a Google Sheet?

**Comment by bgmello** [comment]
I'll create a google sheet with that data
