### ISSUE TITLE
United Nations Protocol and Liaison Service

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#172]
### Data URL

https://www.un.org/dgacm/en/content/protocol

### Publisher

United Nations

### Publisher country/territory code

UN

### Type of data

PEPs (Politicall Exposed Persons)

### Coverage region

region:Global

### Can you tell us more?

List of Heads of Missions https://www.un.org/dgacm/sites/www.un.org.dgacm/files/Documents_Protocol/headsofmissions.pdf
List of Senior UN Officials: https://www.un.org/dgacm/sites/www.un.org.dgacm/files/Documents_Protocol/listofunseniorofficials.pdf

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Duplicate: https://github.com/opensanctions/crawler-planning/issues/191
