### ISSUE TITLE
Philippines National Police Most Wanted List

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#181]
### Data URL

https://procor.pnp.gov.ph/crime-investigation/most-wanted-persons/

### Publisher country/territory code

PH

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:Asia/Pacific

### Can you tell us more?

Website is down right now and looks to be behind CloudFlare - can't scope properly

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
https://github.com/opensanctions/opensanctions/blob/main/zavod/zavod/shed/zyte_api.py#L22
https://github.com/opensanctions/opensanctions/blob/main/zavod/zavod/shed/gpt.py#L37

**Comment by pudo** [comment]
@jbothma I think we'll need a thing that can zyte-fetch images, too: the Philippines police blocks access to them, too.
