### ISSUE TITLE
US Department of Defense Unwanted Foreign Influence at Institutions of Higher Education

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#186]
### Data URL

https://media.defense.gov/2023/Jun/29/2003251160/-1/-1/1/COUNTERING-UNWANTED-INFLUENCE-IN-DEPARTMENT-FUNDED-RESEARCH-AT-INSTITUTIONS-OF-HIGHER-EDUCATION.PDF

### Publisher

US Department of Defense

### Publisher country/territory code

US

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:North America

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Now included in: https://www.opensanctions.org/datasets/us_special_leg/#programs
