### ISSUE TITLE
FinCEN 311 Special Measures

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#204]
### Data URL

https://www.fincen.gov/resources/statutes-and-regulations/311-and-9714-special-measures

### Publisher

FinCEN

### Publisher country/territory code

US

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### Can you tell us more?

List of banks the US gov says not to transact with. This contains a few countries (currently active seems to be Myanmar) - not sure how we can model this. 

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
lol Ukraine has an entry here.

@nvmbrasserie see the rescinded column - we have a pattern where if a sanction or debarment has been lifted, we don't add the topic and we don't set target=True. We do create a Sanction entity for them and provide the applicable end date.
see https://github.com/opensanctions/opensanctions/blob/main/datasets/ae/local_terrorists/crawler.py#L19

**Comment by nvmbrasserie** [comment]
will do, thank you!

**Comment by jbothma** [comment]
closed by https://github.com/opensanctions/opensanctions/pull/1029/
