### ISSUE TITLE
Office of Antiboycott Compliance (OAC) | Bureau of Industry and Security (bis.gov)/ Requester List

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#206]
### Data URL

https://www.bis.gov/OAC

### Publisher

Bureau of Industry and Security

### Publisher country/territory code

US

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:North America

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
XLS parsing example: jp_mof_sanctions
