### ISSUE TITLE
CBP Forced Labor Withhold Release Orders and Findings List

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#207]
### Data URL

https://www.cbp.gov/trade/forced-labor/withhold-release-orders-and-findings

### Publisher

US Customs and Border protection

### Publisher country/territory code

US

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:North America

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Same as https://github.com/opensanctions/crawler-planning/issues/101
