### ISSUE TITLE
Global Energy Ownership Database

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#210]
### Data URL

https://globalenergymonitor.org/download-data-success/

### Publisher

Global Energy Monitor

### Type of data

Companies (National registers of companies, organizations, etc)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
We had a little exchange with them about not making the source data downloadable, that's not implemented in https://github.com/opensanctions/opensanctions/pull/1410 

Next up, I think I'll throw it into `default` raw rather than making it an enricher. It's tiny.

**Comment by jbothma** [comment]
https://www.opensanctions.org/datasets/gem_energy_ownership/
