### ISSUE TITLE
Latvia National Sanctions List

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#214]
### Data URL

https://sankcijas.fid.gov.lv/sankciju-subjekti

### Publisher

Financial Intelligence Service

### Publisher country/territory code

Latvia/lv

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Exists here: https://www.opensanctions.org/datasets/lv_fiu_sanctions/
