### ISSUE TITLE
Lithuania Designated Persons Under Magnitsky Amendments

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#218]
### Data URL

https://www.migracija.lt/app/nam

### Publisher

Ministry of Internal Affairs of the Republic of Lithuania

### Publisher country/territory code

Lithuania/lt

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Comes with a JSON API: https://www.migracija.lt/external/nam/search?pageNo=0&pageSize=100&language=lt
