### ISSUE TITLE
Latvia Designated Persons under Magnitsky Amendments 

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#220]
### Data URL

https://likumi.lv/ta/id/297012-par-aicinajumu-noteikt-sankcijas-sergeja-magnitska-lieta-iesaistitajam-personam

### Publisher country/territory code

Latvia/lv

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
This is done.
