### ISSUE TITLE
Georgia asset declarations

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#230]
There's an API of some sort available here: https://declaration.acb.gov.ge/Home/ApiInstruction 

Can we use this to generate current-year/last-year position holders and import them as PEPs?

**Comment by pudo** [comment]
cc @ketoch

**Comment by jbothma** [comment]
The server seems to get overloaded quite easily and I don't see any pagination options in the API docs.

Perhaps we can try looping over organization ID and year combinations:

`https://declaration.acb.gov.ge/Api/Declarations?OrganizationIds=1&YearSelectedValues=2021` 

But if that gets stuck (it looks like the site times out after 5m) we could just crawl the web pages.

I'll email to ask for pagination options and update here if available.

It's worth double-checking that the entities and positions in scope for reporting here match our PEP position criteria sufficiently well - in the ideal case we can assume all positions are PEPs, but that isn't always the case.
![2024-07-18_16-43](https://github.com/user-attachments/assets/d7bb6a95-4311-4bbc-9c46-57f0b119110a)

**Comment by pudo** [comment]
Let's try and crawl the web pages, then, perhaps? We only need the latest year from the API, but it does seem remarkably unstable even for that.

**Comment by jbothma** [comment]
Added in https://github.com/opensanctions/opensanctions/pull/1072 - will close this if it all looks good
