### ISSUE TITLE
Mexican Tax Offender List 

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#232]
### Data URL

http://omawww.sat.gob.mx/cifras_sat/Paginas/datos/vinculo.html?page=ListCompleta69.html

### Publisher

El Servicio de Administración Tributaria

### Publisher country/territory code

Mexico/mx

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:North America

### Can you tell us more?

This list contains individuals who have committed tax offenses in Mexico.

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
There are several CSV here - we want all of them?

**Comment by jbothma** [comment]
Discuss with @pudo before releasing

**Comment by jbothma** [comment]
500k targets https://www.opensanctions.org/datasets/mx_tax_offenders/

should I dig a bit into whether there are different levels of seriousness we can use to determine the tagging? Or how do we want to decide what we do with it?
