### ISSUE TITLE
FinCEN Money Services Businesses

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#249]
### Data URL

https://www.fincen.gov/msb-state-selector

### Publisher

FinCEN

### Publisher country/territory code

United States/us

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:Global

### Can you tell us more?

Interest in having this included as part of the Business Dataset, possibly closer to a Fitness/Probity list than an actual sanction list.

The FinCEN website publishes a CSV that contains legal names, addresses, and territories for all businesses that register as a Money Service Business.

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
@pudo do we add this to kyb?
also enrich this list against it?
```

  - ann_graph_topics
  - debarment
  - ext_cy_companies
  - ext_cz_business_register
  - ext_ee_ariregister
  - ext_gb_coh_psc
  - ext_gleif
  - ext_icij_offshoreleaks
  - ext_lv_business_register
  - ext_md_companies
  - ext_ru_egrul
  - ext_ua_edr
  - opencorporates
  - sanctions
```
