### ISSUE TITLE
Singapore Economic Development Board

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#259]
### Data URL

[Economic Development Board (EDB) i](https://www.edb.gov.sg/en/about-edb/our-team/executive-management.html)

data url: 
[Executive Committee](https://www.edb.gov.sg/en/about-edb/our-team/executive-management.html)
[Board Members](https://www.edb.gov.sg/en/about-edb/our-team/board-members.html)

### Publisher country/territory code

SG

### Type of data

PEPs (Politicall Exposed Persons)

### Coverage region

region:Asia/Pacific

### Can you tell us more?

Let's take all three tabs (Exec team, board, advisors)

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
closed to be covered by the government directory instead
