### ISSUE TITLE
Singapore Government Directory

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#260]
### Data URL

https://www.sgdi.gov.sg/statutory-boards

### Publisher

Singapore Government

### Publisher country/territory code

Singapore / sg

### Type of data

PEPs (Politicall Exposed Persons)

### Coverage region

region:Africa

### Can you tell us more?

'"I think you'd need to run through each of the listings (Ministries, Statutory Boards, Organs of State, Other Organisations, Public Services Contact, Spokespersons) and then crawl through each of the links on those directory pages. Within each of those linked pages for individual agencies, you can click the "show more" button and then you get a lot of great information with what looks like excellent coverage of Singapore generally'

that site also seems to have other government: https://www.sgdi.gov.sg/ministries
api: https://www.sgdi.gov.sg/api/v1/sgdi/

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Done and live: https://www.opensanctions.org/datasets/sg_gov_dir/
