### ISSUE TITLE
FATCA Foreign Financial Institutions

### ISSUE THREAD

**Issue by jbothma** [opensanctions/crawler-planning#264]
### Data URL

https://www.irs.gov/businesses/corporations/fatca-foreign-financial-institution-list-search-and-download-tool

### Publisher

FATCA

### Publisher country/territory code

US

### Type of data

Companies (National registers of companies, organizations, etc)

### Coverage region

region:Global

### Can you tell us more?

name, country, and GIIN

> The Global Intermediary Identification Number* (GIIN) is a number issued by the US Internal Revenue Service* (IRS) via the IRS registration portal.
>
> All participating foreign financial institutions* need to register with the IRS to obtain a GIIN.
>
> It applies to financial institutions that have adopted FATCA either through an intergovernmental agreement* or as a choice, being a Model 2 foreign financial institution*.
>
> Certain deemed-compliant or non-reporting financial institutions must also obtain a GIIN.
>
> The GIIN is a unique reference number that has a specific format and is issued to identify each financial institution. **Each part of the number has a particular meaning. For example, it tells you whether the financial institution is part of a bigger group or whether the financial institution is a sponsoring entity.** It also identifies the financial institution jurisdiction of residence in which it maintains a branch that is not treated as a 'limited' branch.

https://nedbank.co.za/content/nedbank-lesotho/desktop/lt/en/aboutus/legal/crs-client-communication/faq/entity_clients/what_is_a_GIIN.html

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
I've seen this mentioned in two or three places, and I think it'd gel really nicely with the BIC list we already import. Let's do it!

**Comment by jbothma** [comment]
we've added them to the new banks collection. We need enrichers for these datasets but we'll first dedupe because there should be significant overlap between ISO and FFI

**Comment by jbothma** [comment]
https://www.opensanctions.org/datasets/ext_us_irs_ffi/
