### ISSUE TITLE
US Federal Plum Book

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#273]
### Data URL

https://www.opm.gov/about-us/open-government/plum-reporting/plum-data/

### Publisher

OPM

### Publisher country/territory code

US

### Type of data

PEPs (Politicall Exposed Persons)

### Coverage region

region:North America

### Can you tell us more?

CSV data is available

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
https://www.opensanctions.org/datasets/us_plum_book/
