### ISSUE TITLE
New reconciliation API for Offshore Leaks

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#280]
### Data URL

https://offshoreleaks.icij.org/docs/reconciliation

### Publisher

ICIJ

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:Global

### Can you tell us more?

https://docs.google.com/presentation/d/1Ucc7D9b7VfjZRCp5_ilthJK6u7aVNBbJKSLDeKqgEhU/edit#slide=id.g2cee075f19a_0_677 (slide 15)

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
We've already got this imported via the `icij_offshoreleaks` dataset. Just wanted to look into the way they'd implemented the extension API :)
