### ISSUE TITLE
C4ADS Long Shadows

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#285]
### Data URL

https://d3gnblvlnseq6o.cloudfront.net/

### Publisher

C4ADS

### Publisher country/territory code

US

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:Asia/Pacific

### Can you tell us more?

cf. https://c4ads.org/reports/long-shadows/ 

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
fixes: https://github.com/opensanctions/crawler-planning/issues/285

**Comment by jbothma** [comment]
https://www.opensanctions.org/datasets/c4ads_xinjiang/
