### ISSUE TITLE
US FINRA Disciplinary Actions

### ISSUE THREAD

**Issue by jbothma** [opensanctions/crawler-planning#47]
### Data URL

https://www.finra.org/rules-guidance/oversight-enforcement/finra-disciplinary-actions-online

### Publisher

Financial Industry Regulatory Authority

### Publisher country/territory code

US

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

None

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Looks like we're good: https://www.opensanctions.org/datasets/us_finra_actions/
