### ISSUE TITLE
ES most wanted

### ISSUE THREAD

**Issue by jbothma** [opensanctions/crawler-planning#50]
### Data URL

https://www.policia.es/_es/colabora_masbuscados.php#

### Publisher

Police

### Publisher country/territory code

ES

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

None

### Can you tell us more?

low prio

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Done: https://www.opensanctions.org/datasets/es_cnp_wanted/
