### ISSUE TITLE
Latvia national sanctions list

### ISSUE THREAD

**Issue by jbothma** [opensanctions/crawler-planning#57]
### Data URL

https://sankcijas.fid.gov.lv/

### Publisher

FIU

### Publisher country/territory code

LV

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### Can you tell us more?

medium prio

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Dup: https://www.opensanctions.org/datasets/lv_fiu_sanctions/
