### ISSUE TITLE
Touch up U.S. SEC PAUSE Lists

### ISSUE THREAD

**Issue by baldurh** [opensanctions/crawler-planning#62]
The U.S. Securities and Exchange Commission maintains lists of Harmed Investors and entities that falsely claim to be registered, licensed, and/or located in the United States. Please consider adding them to the OpenSanctions database.

- [Fictitious Regulators](https://www.sec.gov/enforce/public-alerts?aId=edit-field-article-sub-type-secart-value&field_article_sub_type_secart_value=Public+Alerts-FictitiousRegulators)
- [Impersonators of Genuine Firms](https://www.sec.gov/enforce/public-alerts?aId=edit-field-article-sub-type-secart-value&field_article_sub_type_secart_value=Public+Alerts-ImpersonatorsofGenuineFirms)
- [Unregistered Soliciting Entities](https://www.sec.gov/enforce/public-alerts?aId=edit-field-article-sub-type-secart-value&field_article_sub_type_secart_value=Public+Alerts-UnregisteredSolicitingEntities)

Separate: 
- [Information for Harmed Investors](https://www.sec.gov/enforce/information-for-harmed-investors)

**Comment by pudo** [comment]
@opensanctions/crawler-team - this looks like it's three filters on the same backend. Maybe we can make this be one source ("US SEC PAUSE Database") and include the different lists by setting the `program` property on the entities? I think they're all contenders for the `debarment` tag :) - @pudo

**Comment by jbothma** [comment]
Is it an edit of https://www.opensanctions.org/datasets/us_sec_pause/?

**Comment by pudo** [comment]
Totaly agree on `crime.fin`. Should we make a new card for the harmed investors?

**Comment by jbothma** [comment]
fixed up the topic note in my comment above. Will add a car for harmed investors
