### ISSUE TITLE
Austrian PEP list

### ISSUE THREAD

**Issue by FrederikOpenSanctions** [opensanctions/crawler-planning#66]
### Data URL

https://www.meineabgeordneten.at/Abgeordnete

### Publisher

https://www.meineabgeordneten.at

### Publisher country/territory code

Austria

### Type of data

PEPs (Politicall Exposed Persons)

### Coverage region

region:Europe

### Can you tell us more?

Please check legal implications.

### This is a suggestion or request

- [x] I understand.

**Comment by pudo** [comment]
Done: https://www.opensanctions.org/datasets/at_meine_abgeordneten/
