### ISSUE TITLE
Croatia’s State Registry of Public Officials (Registar dužnosnika)

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#69]
https://www.sukobinteresa.hr/Hr/Registar-Duznosnika

**Comment by kdeden** [comment]
Hi @jbothma, you can find my crawler and yml [here](https://github.com/kdeden/opensanctions/tree/hr-public-officials/datasets/hr/public_officials). Can I send you a PR now or do you prefer to do an initial review first?

**Comment by jbothma** [comment]
Sorry I missed this message. Thanks for this!
