### ISSUE TITLE
Israel Knesset Members

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#70]
With DOB and DOD here: https://knesset.gov.il/mk/eng/mkdetails_eng.asp

**Comment by stetelepta** [comment]
There is a useful XML with all members and their page is available here: 
https://knesset.gov.il/WebSiteApi/knessetapi/MKs/GetMksDropdown?languageKey=en

Current 120 members can be found using IsCurrent tag.

Member page:
https://main.knesset.gov.il/en/MK/APPS/mk/mk-personal-details/[id]

**Comment by pudo** [comment]
@stetelepta That should make it super easy and maintainable, thanks for pointing it out! I'll move this one up in our pipeline.

**Comment by pudo** [comment]
Done: https://www.opensanctions.org/datasets/il_knesset_members/
