### ISSUE TITLE
Ukraine NAZK extra datasets

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#72]
It looks like the anti-corruption office of the Ukrainian government has released more entity lists, which are not strictly sanctions lists. I would like to make them into a separate dataset that we crawl, called `ua_nazk_warnings` (while the main bit is still in `ua_nazk_sanctions`). This should then not be added to the `sanctions` collection, but to `default`. 

These are the API endpoints:
* `/api/v6/shame/`
* `/api/v6/boycott/`
* `/api/v6/military-components/`

The API is documented here: https://sanctions.nazk.gov.ua/api/ 

This dataset is multi-lingual, let's make use of `entity.add(prop, val, lang='ukr')` :)

**Comment by jbothma** [comment]
Nope - https://github.com/opensanctions/opensanctions/pull/566 used new company and person endpoints designed specifically for entities related to sanctioned entities.

So it does not add entities from the endpoints listed here.

**Comment by jbothma** [comment]
further reading
- https://sanctions.nazk.gov.ua/en/military-components/
- /en/api/v6/boycott/ intl sponsors https://sanctions.nazk.gov.ua/en/faq/
- shame - https://sanctions.nazk.gov.ua/en/shame/

@pudo no sanction entity, no topic, just a relevant one liner in `entity:program`?

**Comment by pudo** [comment]
I think in the main crawler we're putting topic `poi`, which seems ok (means nothing in particular)

**Comment by jbothma** [comment]
@fjuniorr have you made a start on this one? I see you've moved it to in progress but don't see a PR.

I think this one is ready to go ahead and add as a separate dataset from that fixed in #566.

**Comment by pudo** [comment]
This data portal has been shut down. I'm fixing the crawler to run off the latest available dump of the data, but adding more endpoints will not be possible now.
