### ISSUE TITLE
EU Directive 2023/2878 List

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#74]
The EU publishes a sanctions list which is not included with it's main data file here: https://eur-lex.europa.eu/eli/reg/2023/2878 (Annex IV).

I've made a ready spreadsheet here: 
https://docs.google.com/spreadsheets/d/1rauQMdCYTjTwmSzqfUvur1SfkCGYwfRn6_e5_oX39EY/edit#gid=0

And the CSV URL is: 
https://docs.google.com/spreadsheets/d/e/2PACX-1vQZckYoLdt6O3awOs8piaaWCtFlaKtCNpBWcb36bqakVid31-a-JqmHBri0vch2ggB9R-7yq3jiCarN/pub?gid=0&single=true&output=csv 

This is a proper sanctions set, with the topic and as part of the collection.

**Comment by dhdaines** [comment]
Well, this should be very easy, it's a direct mapping to the ontology... I can do it rather quickly today.

**Comment by pudo** [comment]
Brilliant, thank you!
