### ISSUE TITLE
Lithuanian illegal gambling list

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#78]
> I wonder if it is possible to supplement your lists with additional enforcement list from LT: https://blokuojama.lpt.lt/nelegalios-losimu-veiklos-vykdytoju-sarasas/? 

More description: https://blokuojama.lpt.lt/

**Comment by jbothma** [comment]
@pudo I can't find this PR - am I missing something or did you move this to review by mistake?
