### ISSUE TITLE
French national deputies

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#83]
Official: https://data.assemblee-nationale.fr/ - has JSON profiles.
Also interesting / relevant NGO data site: https://www.nosdeputes.fr/deputes

**Comment by dhdaines** [comment]
In Québec we would translate the position as "members of the National Assembly" (MNAs) even though in French it's "députés".  They seem to translate it as "member of Parliament" in the English translations: https://www2.assemblee-nationale.fr/langues/welcome-to-the-english-website-of-the-french-national-assembly

**Comment by jbothma** [comment]
we tend to prefer using the term used in wikidata.

https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/France

You can see the people we have with that position from wikidata at https://www.opensanctions.org/countries/fr/

I've quickly made the change to the interesting [Senator of the French Fifth Republic](https://www.wikidata.org/wiki/Q14828018) for senators

**Comment by dhdaines** [comment]
> we tend to prefer using the term used in wikidata.
> 
> https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/France

Oh!  Good to know for future reference.

> 
> You can see the people we have with that position from wikidata at https://www.opensanctions.org/countries/fr/
> 
> I've quickly made the change to the interesting [Senator of the French Fifth Republic](https://www.wikidata.org/wiki/Q14828018) for senators

Ah, yes, in this case "Fifth Republic" is probably important.

**Comment by dhdaines** [comment]
Ah. Just noticed that associates and close links are also available in the data, so I will add these before putting this up for review.

**Comment by pudo** [comment]
I'm not sure they're not - from an anti-corruption perspective they're really interesting and the "close associates" part of "RCA" definitely applies.

**Comment by dhdaines** [comment]
Okay! Should I add them as `Associate` with `relationship="collaborateur"`?

**Comment by dhdaines** [comment]
Ready for review!
