### ISSUE TITLE
French senate

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#84]
https://www.senat.fr/senateurs/senatl.html - maybe check if they're also in https://www.nosdeputes.fr/deputes

**Comment by dhdaines** [comment]
Open data here (JSON, CSV, XLSX) https://data.senat.fr/les-senateurs/ - I'll use the JSON

**Comment by dhdaines** [comment]
> Open data here (JSON, CSV, XLSX) https://data.senat.fr/les-senateurs/ - I'll use the JSON

Or, maybe, the CSV, as it is smaller (they are actually dumps of specific SQL queries on the full dataset)
