### ISSUE TITLE
French mayors

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#85]
Available as CSV: https://www.data.gouv.fr/fr/datasets/liste-des-maires/
Also crawlable here: https://www.amf.asso.fr/m/annuaire/

@jbothma This is a customer idea. I wonder if in the position tagger we should introduce a list of countries for which we export `local` tagged PEPs?

**Comment by jbothma** [comment]
Local PEPs are currently emitted by any crawler that finds them, except wd_peps. So this crawler will work without any changes to the DB. Ready to go.

**Comment by dhdaines** [comment]
The list above is wildly out of date, but in the comments it's mentioned that an up-to-date list is available here: https://www.data.gouv.fr/fr/datasets/repertoire-national-des-elus-1/

**Comment by jbothma** [comment]
Nice find! Thanks!
