### ISSUE TITLE
US HHS OIG List of Excluded Individuals/Entities

### ISSUE THREAD

**Issue by pudo** [opensanctions/crawler-planning#88]
> OIG maintains a list of all currently excluded individuals and entities called the [List of Excluded Individuals/Entities](https://oig.hhs.gov/exclusions/exclusions_list.asp) (LEIE). Anyone who hires an individual or entity on the LEIE may be subject to civil monetary penalties (CMP). To avoid CMP liability, health care entities should routinely check the list to ensure that new hires and current employees are not on it.

Located here: https://oig.hhs.gov/exclusions/index.asp 

This is a `debarment` candidate.

**Comment by jbothma** [comment]
looks like more info about reasons at https://oig.hhs.gov/faqs/exclusions-faq/

using this as a first task for Kishan

**Comment by KishanAdhikari11** [comment]
I have opened Pull Request for this at https://github.com/opensanctions/opensanctions/issues/88. Please have a look at it.
