### ISSUE TITLE
US FinCEN 311 Actions

### ISSUE THREAD

**Issue by Ketoch** [opensanctions/crawler-planning#97]
### Data URL

https://home.treasury.gov/policy-issues/terrorism-and-illicit-finance/311-actions

### Publisher

U.S. DEPARTMENT OF THE TREASURY

### Type of data

Sanctions (Governments barring specific engagement e.g. financial transaction with these entities)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by jbothma** [comment]
Is this covered by https://github.com/opensanctions/crawler-planning/issues/204 ?

**Comment by nvmbrasserie** [comment]
It's the same as #204, so I moved it to Done
