### ISSUE TITLE
US DEA Most Wanted

### ISSUE THREAD

**Issue by Ketoch** [opensanctions/crawler-planning#98]
### Data URL

https://www.dea.gov/fugitives

### Publisher

DEA united states drug enforcement administration

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:Global

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment]
Full listing: https://www.dea.gov/fugitives/all
